<h3 class="text-light bg-dark">Add Product</h3>
<div class="alert alert-<?php echo $success === true ? 'success' : ''; ?>">
    <?php echo $message; ?>
</div>
<?php echo $this->tag->form("products/add"); ?>
    <div class="form-group">
        <label for="productname">Product Name</label>
        <?php echo $this->tag->textField(['name' => 'productname', 'maxlength' => 30, 'placeholder' => 'Product Name', 'class' => 'form-control']); ?>
    </div>
    <div class="form-group">
        <label for="category">Category Name</label>
        <?php echo $this->tag->textField(['name' => 'category', 'rows' => '3', 'maxlength' => 30, 'placeholder' => 'Add Product Category', 'class' => 'form-control']); ?>
    </div>
    <div class="form-group">
        <label for="price">Price</label>
        <?php echo $this->tag->textField(['name' => 'price', 'maxlength' => 30, 'placeholder' => 'Price', 'class' => 'form-control']); ?>
    </div>
    <div class="form-group border">
        <label for="additionalField" class="font-weight-bold">Additional Fields</label>
        <div id="additionalFields">
            <div class="form-group col-auto">
                <label for="attributename">Attribute name</label>
                <?php echo $this->tag->textField(['name' => 'meta_label[]', 'maxlength' => 30, 'placeholder' => 'Meta field label', 'class' => 'form-control']); ?>
            </div>
            <div class="form-group col-auto">
                <label for="attributevalue">Attribute value</label>
                <?php echo $this->tag->textField(['name' => 'meta_value[]', 'maxlength' => 30, 'placeholder' => 'Meta field Value', 'class' => 'form-control']); ?>                
            </div>
            <button type="button" onclick="addAdditionalField()">+</button>
        </div>
    </div>
    <div class="form-group border">
        <label for="variation" class="font-weight-bold">Variations</label>
        <div id="variations">
            <div class="form-group col-auto">
                <label for="variationname">variation name</label>
                <?php echo $this->tag->textField(['name' => 'variationname[]', 'maxlength' => 30, 'placeholder' => 'Attribute Name', 'class' => 'form-control']); ?>
            </div>
            <div class="form-group col-auto">
                <label for="variationvalue">variation value</label>
                <?php echo $this->tag->textField(['name' => 'variationvalue[]', 'maxlength' => 30, 'placeholder' => 'Attribute Value', 'class' => 'form-control']); ?>
            </div>
            <div class="form-group col-auto">
                <label for="variationprice">Price</label>
                <?php echo $this->tag->textField(['name' => 'variationprice[]', 'maxlength' => 30, 'placeholder' => 'Variation Price', 'class' => 'form-control']); ?>
            </div>
        </div>
        <button type="button" class="btn btn-secondary" onclick="addVariation()">Add Variation</button>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

<script>

    function addAdditionalField() {
        const additionalDiv = document.getElementById('additionalFields');
        const newAdditionalDiv = document.createElement('div');
        newAdditionalDiv.className = "form-group border";
        newAdditionalDiv.innerHTML = `
                <div class="form-group col-auto">
                    <label for="attributename">Attribute name</label>
                    <?php echo $this->tag->textField(['name' => 'meta_label[]', 'maxlength' => 30, 'placeholder' => 'Meta field label', 'class' => 'form-control']); ?>
                </div>
                <div class="form-group col-auto">
                    <label for="attributevalue">Attribute value</label>
                    <?php echo $this->tag->textField(['name' => 'meta_value[]', 'maxlength' => 30, 'placeholder' => 'Meta field Value', 'class' => 'form-control']); ?>                
                </div>
                 <button type="button" class="btn btn-danger" onclick="removeAdditionalField(this)">Remove Additional Field</button>
        `;
        additionalDiv.appendChild(newAdditionalDiv);
    }
    function addVariation() {
        const variationsDiv = document.getElementById('variations');
        const newVariationDiv = document.createElement('div');
        newVariationDiv.className = "form-group border";
        newVariationDiv.innerHTML = `
        <div class="form-group col-auto">
                <label for="variationname">variation name</label>
                <?php echo $this->tag->textField(['name' => 'variationname[]', 'maxlength' => 30, 'placeholder' => 'Attribute Name', 'class' => 'form-control']); ?>
            </div>
            <div class="form-group col-auto">
                <label for="variationvalue">variation value</label>
                <?php echo $this->tag->textField(['name' => 'variationvalue[]', 'maxlength' => 30, 'placeholder' => 'Attribute Value', 'class' => 'form-control']); ?>
            </div>
            <div class="form-group col-auto">
                <label for="variationprice">Price</label>
                <?php echo $this->tag->textField(['name' => 'variationprice[]', 'maxlength' => 30, 'placeholder' => 'Variation Price', 'class' => 'form-control']); ?>
            </div>
            <button type="button" class="btn btn-danger" onclick="removeVariation(this)">Remove Variation</button>
        `;
        variationsDiv.appendChild(newVariationDiv);
    }

    function removeVariation(button) {
        button.parentElement.remove();
    }

    function removeAdditionalField(button) {
        button.parentElement.remove();
    }
    
</script>
